# versions

source ~/.bashrc

BINUTILS_VERSION=binutils-2.36.1
GCC_VERSION=gcc-10.2.0
MPFR_VERSION=mpfr-4.1.0
GMP_VERSION=gmp-6.2.1
MPC_VERSION=mpc-1.2.1
GLIBC_VERSION=glibc-2.33
M4_VERSION=m4-1.4.18
NCURSES_VERSION=ncurses-6.2
BASH_VERSION=bash-5.1
COREUTILS_VERSION=coreutils-8.32
DIFFUTILS_VERSION=diffutils-3.7
FILE_VERSION=file-5.39
FINDUTILS_VERSION=findutils-4.8.0
GAWK_VERSION=gawk-5.1.0
GREP_VERSION=grep-3.6
GZIP_VERSION=gzip-1.10
MAKE_VERSION=make-4.3
PATCH_VERSION=patch-2.7.6
SED_VERSION=sed-4.8
TAR_VERSION=tar-1.34
XZ_VERSION=xz-5.2.5
LINUX_VERSION=linux-5.10.17

export BINUTILS_VERSION GCC_VERSION MPFR_VERSION GMP_VERSION \
	MPC_VERSION GLIBC_VERSION M4_VERSION NCURSES_VERSION \
	BASH_VERSION COREUTILS_VERSION DIFFUTILS_VERSION FILE_VERSION \
	FINDUTILS_VERSION GAWK_VERSION GREP_VERSION GZIP_VERSION \
	MAKE_VERSION PATCH_VERSION SED_VERSION XZ_VERSION \
	LINUX_VERSION
